# docker compose creates image for service using dockerfile
version: "3.8"
# how to build image for service, and how to run container for it
services:
  api:
    build: ./Docker
    container_name: api_c
    # port mappings
    ports:
      - '4000:4000'
    volumes:
      # create volume to map Docker folder on host machine to app folder on container
      - ./Docker:/app
      - /app/node_modules
  myblog:
    # specify path to Dockerfile
    build: ./myblog
    container_name: myblog_c
    ports:
     - '3000:3000'
    # start container in interactive mode (opposite of detached mode)
    # react container will not automatically shut down
    stdin_open: true
    tty: true